package com.example.offlinetts.utils

import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.RandomAccessFile
import java.nio.ByteBuffer
import java.nio.ByteOrder

object AudioStitcher {

    fun mergeAudioFiles(inputs: List<File>, outputFile: File): Boolean {
        if (inputs.isEmpty()) return false

        try {
            val outputStream = FileOutputStream(outputFile)
            
            // Placeholder calculation for total size
            var totalDataSize = 0
            
            // Write a dummy header first
            writeWavHeader(outputStream, 0, 24000, 1) // Assuming 24kHz mono

            val buffer = ByteArray(4096)
            
            inputs.forEach { inputFile ->
                val inputStream = FileInputStream(inputFile)
                
                // Skip the 44-byte WAV header of the chunk
                // We assume all chunks are 16-bit PCM WAVs generated by RenderingWorker
                val skipped = inputStream.skip(44)
                if (skipped < 44) {
                    // unexpected, might be empty or malformed
                }

                var bytesRead: Int
                while (inputStream.read(buffer).also { bytesRead = it } != -1) {
                    outputStream.write(buffer, 0, bytesRead)
                    totalDataSize += bytesRead
                }
                inputStream.close()
            }
            
            outputStream.close()

            // Update header with correct size
            val randomAccessFile = RandomAccessFile(outputFile, "rw")
            randomAccessFile.seek(0)
            // Re-write header with correct size
            // We need a helper to write the header bytes directly
            val headerBytes = generateWavHeaderBytes(totalDataSize, 24000, 1)
            randomAccessFile.write(headerBytes)
            randomAccessFile.close()

            return true

        } catch (e: Exception) {
            e.printStackTrace()
            return false
        }
    }

    private fun writeWavHeader(out: FileOutputStream, totalAudioLen: Int, sampleRate: Int, channels: Int) {
        out.write(generateWavHeaderBytes(totalAudioLen, sampleRate, channels))
    }

    private fun generateWavHeaderBytes(totalAudioLen: Int, sampleRate: Int, channels: Int): ByteArray {
        val totalDataLen = totalAudioLen + 36
        val byteRate = sampleRate * channels * 2
        
        val header = ByteArray(44)
        header[0] = 'R'.code.toByte()
        header[1] = 'I'.code.toByte()
        header[2] = 'F'.code.toByte()
        header[3] = 'F'.code.toByte()
        header[4] = (totalDataLen and 0xff).toByte()
        header[5] = ((totalDataLen shr 8) and 0xff).toByte()
        header[6] = ((totalDataLen shr 16) and 0xff).toByte()
        header[7] = ((totalDataLen shr 24) and 0xff).toByte()
        header[8] = 'W'.code.toByte()
        header[9] = 'A'.code.toByte()
        header[10] = 'V'.code.toByte()
        header[11] = 'E'.code.toByte()
        header[12] = 'f'.code.toByte()
        header[13] = 'm'.code.toByte()
        header[14] = 't'.code.toByte()
        header[15] = ' '.code.toByte()
        header[16] = 16 // 4 bytes: size of 'fmt ' chunk
        header[17] = 0
        header[18] = 0
        header[19] = 0
        header[20] = 1 // format = 1 (PCM)
        header[21] = 0
        header[22] = channels.toByte()
        header[23] = 0
        header[24] = (sampleRate and 0xff).toByte()
        header[25] = ((sampleRate shr 8) and 0xff).toByte()
        header[26] = ((sampleRate shr 16) and 0xff).toByte()
        header[27] = ((sampleRate shr 24) and 0xff).toByte()
        header[28] = (byteRate and 0xff).toByte()
        header[29] = ((byteRate shr 8) and 0xff).toByte()
        header[30] = ((byteRate shr 16) and 0xff).toByte()
        header[31] = ((byteRate shr 24) and 0xff).toByte()
        header[32] = (2 * channels).toByte() // block align
        header[33] = 0
        header[34] = 16 // bits per sample
        header[35] = 0
        header[36] = 'd'.code.toByte()
        header[37] = 'a'.code.toByte()
        header[38] = 't'.code.toByte()
        header[39] = 'a'.code.toByte()
        header[40] = (totalAudioLen and 0xff).toByte()
        header[41] = ((totalAudioLen shr 8) and 0xff).toByte()
        header[42] = ((totalAudioLen shr 16) and 0xff).toByte()
        header[43] = ((totalAudioLen shr 24) and 0xff).toByte()
        return header
    }
}
